export const initialData = {
    data: [
        {
            author: "Upasana Banerjee",
            title: "Nick Kyrgios Dubbed an ‘Egocentric’ as Jannik Sinner’s Compatriot Weighs In on Doping Controversy",
            description:
                "Jannik Sinner’s 2024 season was nothing short of e… Controversy appeared first on EssentiallySports.",
            url: "https://www.essentiallysports.com/atp-wta-tennis-n…nners-compatriot-weighs-in-on-doping-controversy/",
            source: "Essentially Sports",
            publishedAt: "2024-12-24T10:30:00Z",
            country: "USA",
            category: "Sports",
        },
        {
            author: "/u/RKaasen",
            title: "Good resource for analyzing football (any sports) …more customizability? And more stats/data/leagues",
            description: "&#32; submitted by &#32; /u/RKaasen [link] &#32; [comments]",
            url: "https://www.reddit.com/r/sports/comments/1hlaxr9/good_resource_for_analyzing_football_any_sports/",
            source: "Sports | Reddit",
            publishedAt: "2024-12-24T08:15:00Z",
            country: "Global",
            category: "Sports",
        },
        {
            author: "Phil Spencer",
            title: "&#8216;Staggered&#8217; Gareth A Davies responds t…iral clash with Johnny Fisher&#8217;s furious dad",
            description:
                "&#8216;Staggered&#8217; Gareth A Davies responds t…iral clash with Johnny Fisher&#8217;s furious dad",
            url: "https://talksport.com/boxing/2418092/gareth-a-davies-big-john-fisher-viral-interview/",
            source: "TalkSport",
            publishedAt: "2024-12-24T09:00:00Z",
            country: "UK",
            category: "Boxing",
        },
        {
            author: "SportsCafe Desk",
            title: "Laura Celia Valk Addresses Jude Bellingham Relationship Rumours",
            description:
                "Laura Celia Valk and Jude Bellingham have been rum…oyfriend as of now, turning down all the rumours.",
            url: "https://sportscafe.in/football/articles/2024/dec/2…de-bellingham-relationship-rumours?utm_medium=rss",
            source: "Sportscafe",
            publishedAt: "2024-12-24T11:30:00Z",
            country: "India",
            category: "Football",
        },
        {
            author: "Soheli Tarafdar",
            title: "Crucial Details Emerge as $725M Greed Rides on House vs. NCAA Settlement Battle",
            description:
                "It has been a long time since the House vs. NCAA g…ement Battle appeared first on EssentiallySports.",
            url: "https://www.essentiallysports.com/ncaa-college-foo…s-greed-rides-on-house-vs-ncaa-settlement-battle/",
            source: "Essentially Sports",
            publishedAt: "2024-12-24T07:45:00Z",
            country: "USA",
            category: "College Football",
        },
        {
            author: "Tanisha Kapoor",
            title: "Retired WTA Legend Victoria Azarenka Clears the Air on Her Son’s Tennis Future With a Bold Take",
            description:
                "Apart from being a brilliant tennis player, Victor… a Bold Take appeared first on EssentiallySports.",
            url: "https://www.essentiallysports.com/wta-tennis-news-…e-air-on-her-sons-tennis-future-with-a-bold-take/",
            source: "Essentially Sports",
            publishedAt: "2024-12-24T10:00:00Z",
            country: "USA",
            category: "Tennis",
        },
        {
            author: "Payal Tomar",
            title: "IND vs AUS 4th Test: Everything you need to know about Boxing Day Test",
            description:
                "India will face Australia in the Boxing Day Test m…ng Day Test appeared first on Inside Sport India.",
            url: "https://www.insidesport.in/cricket/ind-vs-aus-4th-…verything-you-need-to-know-about-boxing-day-test/",
            source: "Insidesport",
            publishedAt: "2024-12-24T08:45:00Z",
            country: "India",
            category: "Cricket",
        },
        {
            author: "Betting Reporter",
            title: "Spreadex New Customer Christmas Offer: Bet £10 Get £40 in Free Bets",
            description: "Spreadex New Customer Christmas Offer: Bet £10 Get £40 in Free Bets",
            url: "https://talksport.com/betting/2418161/spreadex-christmas-betting-offer-2024/",
            source: "TalkSport",
            publishedAt: "2024-12-24T12:00:00Z",
            country: "UK",
            category: "Betting",
        },
        {
            author: "Betting Reporter",
            title: "Celebrate Christmas with SBK &#8211; A festive welcome offer for new customers!",
            description:
                "Celebrate Christmas with SBK &#8211; A festive welcome offer for new customers!",
            url: "https://talksport.com/betting/2418079/sbk-christmas-welcome-offer-2024/",
            source: "TalkSport",
            publishedAt: "2024-12-24T14:00:00Z",
            country: "UK",
            category: "Betting",
        },
        {
            author: "Katie Rosseinsky",
            title: "Nigella Lawson reveals bizarre secret to the perfect Christmas dinner",
            description: "Her expert hack requires a day or two of preparation",
            url: "https://www.independent.co.uk/life-style/nigella-lawson-turkey-brine-recipe-b2669515.html",
            source: "The Independent - Life and Style",
            publishedAt: "2024-12-24T13:00:00Z",
            country: "UK",
            category: "Lifestyle",
        },
        {
            author: "Betting Reporter",
            title: "Mega Riches Casino &#8211; 100% up to £25 sign up Christmas bonus for new customers",
            description:
                "Mega Riches Casino &#8211; 100% up to £25 sign up Christmas bonus for new customers",
            url: "https://talksport.com/betting/2418076/megariches-christmas-welcome-offer-2024/",
            source: "TalkSport",
            publishedAt: "2024-12-24T10:45:00Z",
            country: "UK",
            category: "Betting",
        },
        {
            author: "Mintu Tomar",
            title: "Coco Gauff Flaunts Sleek New Gear From $4.3 Billion Sponsor After Moving On From Her “Babies”",
            description:
                "“I won my first major in the CG1. So, that shoe wi…Her “Babies” appeared first on EssentiallySports.",
            url: "https://www.essentiallysports.com/wta-tennis-news-…-billion-sponsor-after-moving-on-from-her-babies/",
            source: "Essentially Sports",
            publishedAt: "2024-12-24T07:00:00Z",
            country: "USA",
            category: "Tennis",
        },
        {
            author: "Betting Reporter",
            title: "Christmas fun with Virgin Games: Enjoy their amazing welcome offer!",
            description: "Christmas fun with Virgin Games: Enjoy their amazing welcome offer!",
            url: "https://talksport.com/betting/2418047/virgin-games-christmas-welcome-offer-2024/",
            source: "TalkSport",
            publishedAt: "2024-12-24T11:15:00Z",
            country: "UK",
            category: "Betting",
        },
        {
            author: "Pranchal Srivastava",
            title: "IND vs AUS 4th Test date, time & venue",
            description:
                "Check out the upcoming IND vs AUS 4th Test date, t…ime & venue appeared first on Inside Sport India.",
            url: "https://www.insidesport.in/cricket/ind-vs-aus-4th-test-date-time-venue/",
            source: "Insidesport",
            publishedAt: "2024-12-24T12:30:00Z",
            country: "India",
            category: "Cricket",
        },
    ],
};
